// universitylist.ts
export const countryCodes = [
    { code: "+93", country: "Afghanistan", flag: "🇦🇫" },
    { code: "+355", country: "Albania", flag: "🇦🇱" },
    { code: "+213", country: "Algeria", flag: "🇩🇿" },
    { code: "+376", country: "Andorra", flag: "🇦🇩" },
    { code: "+244", country: "Angola", flag: "🇦🇴" },
    { code: "+1268", country: "Antigua and Barbuda", flag: "🇦🇬" },
    { code: "+54", country: "Argentina", flag: "🇦🇷" },
    { code: "+374", country: "Armenia", flag: "🇦🇲" },
    { code: "+297", country: "Aruba", flag: "🇦🇼" },
    { code: "+61", country: "Australia", flag: "🇦🇺" },
    { code: "+43", country: "Austria", flag: "🇦🇹" },
    { code: "+994", country: "Azerbaijan", flag: "🇦🇿" },
    { code: "+1242", country: "Bahamas", flag: "🇧🇸" },
    { code: "+973", country: "Bahrain", flag: "🇧🇭" },
    { code: "+880", country: "Bangladesh", flag: "🇧🇩" },
    { code: "+1246", country: "Barbados", flag: "🇧🇧" },
    { code: "+375", country: "Belarus", flag: "🇧🇾" },
    { code: "+32", country: "Belgium", flag: "🇧🇪" },
    { code: "+501", country: "Belize", flag: "🇧🇿" },
    { code: "+229", country: "Benin", flag: "🇧🇯" },
    { code: "+975", country: "Bhutan", flag: "🇧🇹" },
    { code: "+591", country: "Bolivia", flag: "🇧🇴" },
    { code: "+387", country: "Bosnia and Herzegovina", flag: "🇧🇦" },
    { code: "+267", country: "Botswana", flag: "🇧🇼" },
    { code: "+55", country: "Brazil", flag: "🇧🇷" },
    { code: "+246", country: "British Indian Ocean Territory", flag: "🇮🇴" },
    { code: "+673", country: "Brunei", flag: "🇧🇳" },
    { code: "+359", country: "Bulgaria", flag: "🇧🇬" },
    { code: "+226", country: "Burkina Faso", flag: "🇧🇫" },
    { code: "+257", country: "Burundi", flag: "🇧🇮" },
    { code: "+855", country: "Cambodia", flag: "🇰🇭" },
    { code: "+237", country: "Cameroon", flag: "🇨🇲" },
    { code: "+1", country: "Canada", flag: "🇨🇦" },
    { code: "+238", country: "Cape Verde", flag: "🇨🇻" },
    { code: "+599", country: "Caribbean Netherlands", flag: "🇧🇶" },
    { code: "+236", country: "Central African Republic", flag: "🇨🇫" },
    { code: "+235", country: "Chad", flag: "🇹🇩" },
    { code: "+56", country: "Chile", flag: "🇨🇱" },
    { code: "+86", country: "China", flag: "🇨🇳" },
    { code: "+57", country: "Colombia", flag: "🇨🇴" },
    { code: "+269", country: "Comoros", flag: "🇰🇲" },
    { code: "+243", country: "Congo (DRC)", flag: "🇨🇩" },
    { code: "+242", country: "Congo", flag: "🇨🇬" },
    { code: "+506", country: "Costa Rica", flag: "🇨🇷" },
    { code: "+225", country: "Côte d’Ivoire", flag: "🇨🇮" },
    { code: "+385", country: "Croatia", flag: "🇭🇷" },
    { code: "+53", country: "Cuba", flag: "🇨🇺" },
    { code: "+599", country: "Curaçao", flag: "🇨🇼" },
    { code: "+357", country: "Cyprus", flag: "🇨🇾" },
    { code: "+420", country: "Czech Republic", flag: "🇨🇿" },
    { code: "+45", country: "Denmark", flag: "🇩🇰" },
    { code: "+253", country: "Djibouti", flag: "🇩🇯" },
    { code: "+1767", country: "Dominica", flag: "🇩🇲" },
    { code: "+1", country: "Dominican Republic", flag: "🇩🇴" },
    { code: "+593", country: "Ecuador", flag: "🇪🇨" },
    { code: "+20", country: "Egypt", flag: "🇪🇬" },
    { code: "+503", country: "El Salvador", flag: "🇸🇻" },
    { code: "+240", country: "Equatorial Guinea", flag: "🇬🇶" },
    { code: "+291", country: "Eritrea", flag: "🇪🇷" },
    { code: "+372", country: "Estonia", flag: "🇪🇪" },
    { code: "+251", country: "Ethiopia", flag: "🇪🇹" },
    { code: "+679", country: "Fiji", flag: "🇫🇯" },
    { code: "+358", country: "Finland", flag: "🇫🇮" },
    { code: "+33", country: "France", flag: "🇫🇷" },
    { code: "+594", country: "French Guiana", flag: "🇬🇫" },
    { code: "+689", country: "French Polynesia", flag: "🇵🇫" },
    { code: "+241", country: "Gabon", flag: "🇬🇦" },
    { code: "+220", country: "Gambia", flag: "🇬🇲" },
    { code: "+995", country: "Georgia", flag: "🇬🇪" },
    { code: "+49", country: "Germany", flag: "🇩🇪" },
    { code: "+233", country: "Ghana", flag: "🇬🇭" },
    { code: "+30", country: "Greece", flag: "🇬🇷" },
    { code: "+1473", country: "Grenada", flag: "🇬🇩" },
    { code: "+590", country: "Guadeloupe", flag: "🇬🇵" },
    { code: "+1671", country: "Guam", flag: "🇬🇺" },
    { code: "+502", country: "Guatemala", flag: "🇬🇹" },
    { code: "+224", country: "Guinea", flag: "🇬🇳" },
    { code: "+245", country: "Guinea-Bissau", flag: "🇬🇼" },
    { code: "+592", country: "Guyana", flag: "🇬🇾" },
    { code: "+509", country: "Haiti", flag: "🇭🇹" },
    { code: "+504", country: "Honduras", flag: "🇭🇳" },
    { code: "+852", country: "Hong Kong", flag: "🇭🇰" },
    { code: "+36", country: "Hungary", flag: "🇭🇺" },
    { code: "+354", country: "Iceland", flag: "🇮🇸" },
    { code: "+91", country: "India", flag: "🇮🇳" },
    { code: "+62", country: "Indonesia", flag: "🇮🇩" },
    { code: "+98", country: "Iran", flag: "🇮🇷" },
    { code: "+964", country: "Iraq", flag: "🇮🇶" },
    { code: "+353", country: "Ireland", flag: "🇮🇪" },
    { code: "+972", country: "Israel", flag: "🇮🇱" },
    { code: "+39", country: "Italy", flag: "🇮🇹" },
    { code: "+1876", country: "Jamaica", flag: "🇯🇲" },
    { code: "+81", country: "Japan", flag: "🇯🇵" },
    { code: "+962", country: "Jordan", flag: "🇯🇴" },
    { code: "+7", country: "Kazakhstan", flag: "🇰🇿" },
    { code: "+254", country: "Kenya", flag: "🇰🇪" },
    { code: "+686", country: "Kiribati", flag: "🇰🇮" },
    { code: "+383", country: "Kosovo", flag: "🇽🇰" },
    { code: "+965", country: "Kuwait", flag: "🇰🇼" },
    { code: "+996", country: "Kyrgyzstan", flag: "🇰🇬" },
    { code: "+856", country: "Laos", flag: "🇱🇦" },
    { code: "+371", country: "Latvia", flag: "🇱🇻" },
    { code: "+961", country: "Lebanon", flag: "🇱🇧" },
    { code: "+266", country: "Lesotho", flag: "🇱🇸" },
    { code: "+231", country: "Liberia", flag: "🇱🇷" },
    { code: "+218", country: "Libya", flag: "🇱🇾" },
    { code: "+423", country: "Liechtenstein", flag: "🇱🇮" },
    { code: "+370", country: "Lithuania", flag: "🇱🇹" },
    { code: "+352", country: "Luxembourg", flag: "🇱🇺" },
    { code: "+853", country: "Macau", flag: "🇲🇴" },
    { code: "+389", country: "Macedonia", flag: "🇲🇰" },
    { code: "+261", country: "Madagascar", flag: "🇲🇬" },
    { code: "+265", country: "Malawi", flag: "🇲🇼" },
    { code: "+60", country: "Malaysia", flag: "🇲🇾" },
    { code: "+960", country: "Maldives", flag: "🇲🇻" },
    { code: "+223", country: "Mali", flag: "🇲🇱" },
    { code: "+356", country: "Malta", flag: "🇲🇹" },
    { code: "+692", country: "Marshall Islands", flag: "🇲🇭" },
    { code: "+596", country: "Martinique", flag: "🇲🇶" },
    { code: "+222", country: "Mauritania", flag: "🇲🇷" },
    { code: "+230", country: "Mauritius", flag: "🇲🇺" },
    { code: "+52", country: "Mexico", flag: "🇲🇽" },
    { code: "+691", country: "Micronesia", flag: "🇫🇲" },
    { code: "+373", country: "Moldova", flag: "🇲🇩" },
    { code: "+377", country: "Monaco", flag: "🇲🇨" },
    { code: "+976", country: "Mongolia", flag: "🇲🇳" },
    { code: "+382", country: "Montenegro", flag: "🇲🇪" },
    { code: "+212", country: "Morocco", flag: "🇲🇦" },
    { code: "+258", country: "Mozambique", flag: "🇲🇿" },
    { code: "+95", country: "Myanmar", flag: "🇲🇲" },
    { code: "+264", country: "Namibia", flag: "🇳🇦" },
    { code: "+674", country: "Nauru", flag: "🇳🇷" },
    { code: "+977", country: "Nepal", flag: "🇳🇵" },
    { code: "+31", country: "Netherlands", flag: "🇳🇱" },
    { code: "+687", country: "New Caledonia", flag: "🇳🇨" },
    { code: "+64", country: "New Zealand", flag: "🇳🇿" },
    { code: "+505", country: "Nicaragua", flag: "🇳🇮" },
    { code: "+227", country: "Niger", flag: "🇳🇪" },
    { code: "+234", country: "Nigeria", flag: "🇳🇬" },
    { code: "+850", country: "North Korea", flag: "🇰🇵" },
    { code: "+47", country: "Norway", flag: "🇳🇴" },
    { code: "+968", country: "Oman", flag: "🇴🇲" },
    { code: "+92", country: "Pakistan", flag: "🇵🇰" },
    { code: "+680", country: "Palau", flag: "🇵🇼" },
    { code: "+970", country: "Palestine", flag: "🇵🇸" },
    { code: "+507", country: "Panama", flag: "🇵🇦" },
    { code: "+675", country: "Papua New Guinea", flag: "🇵🇬" },
    { code: "+595", country: "Paraguay", flag: "🇵🇾" },
    { code: "+51", country: "Peru", flag: "🇵🇪" },
    { code: "+63", country: "Philippines", flag: "🇵🇭" },
    { code: "+48", country: "Poland", flag: "🇵🇱" },
    { code: "+351", country: "Portugal", flag: "🇵🇹" },
    { code: "+1", country: "Puerto Rico", flag: "🇵🇷" },
    { code: "+974", country: "Qatar", flag: "🇶🇦" },
    { code: "+262", country: "Réunion", flag: "🇷🇪" },
    { code: "+40", country: "Romania", flag: "🇷🇴" },
    { code: "+7", country: "Russia", flag: "🇷🇺" },
    { code: "+250", country: "Rwanda", flag: "🇷🇼" },
    { code: "+1869", country: "Saint Kitts and Nevis", flag: "🇰🇳" },
    { code: "+1758", country: "Saint Lucia", flag: "🇱🇨" },
    { code: "+1784", country: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
    { code: "+685", country: "Samoa", flag: "🇼🇸" },
    { code: "+378", country: "San Marino", flag: "🇸🇲" },
    { code: "+239", country: "São Tomé and Príncipe", flag: "🇸🇹" },
    { code: "+966", country: "Saudi Arabia", flag: "🇸🇦" },
    { code: "+221", country: "Senegal", flag: "🇸🇳" },
    { code: "+381", country: "Serbia", flag: "🇷🇸" },
    { code: "+248", country: "Seychelles", flag: "🇸🇨" },
    { code: "+232", country: "Sierra Leone", flag: "🇸🇱" },
    { code: "+65", country: "Singapore", flag: "🇸🇬" },
    { code: "+421", country: "Slovakia", flag: "🇸🇰" },
    { code: "+386", country: "Slovenia", flag: "🇸🇮" },
    { code: "+677", country: "Solomon Islands", flag: "🇸🇧" },
    { code: "+252", country: "Somalia", flag: "🇸🇴" },
    { code: "+27", country: "South Africa", flag: "🇿🇦" },
    { code: "+82", country: "South Korea", flag: "🇰🇷" },
    { code: "+211", country: "South Sudan", flag: "🇸🇸" },
    { code: "+34", country: "Spain", flag: "🇪🇸" },
    { code: "+94", country: "Sri Lanka", flag: "🇱🇰" },
    { code: "+249", country: "Sudan", flag: "🇸🇩" },
    { code: "+597", country: "Suriname", flag: "🇸🇷" },
    { code: "+268", country: "Swaziland", flag: "🇸🇿" },
    { code: "+46", country: "Sweden", flag: "🇸🇪" },
    { code: "+41", country: "Switzerland", flag: "🇨🇭" },
    { code: "+963", country: "Syria", flag: "🇸🇾" },
    { code: "+886", country: "Taiwan", flag: "🇹🇼" },
    { code: "+992", country: "Tajikistan", flag: "🇹🇯" },
    { code: "+255", country: "Tanzania", flag: "🇹🇿" },
    { code: "+66", country: "Thailand", flag: "🇹🇭" },
    { code: "+670", country: "Timor-Leste", flag: "🇹🇱" },
    { code: "+228", country: "Togo", flag: "🇹🇬" },
    { code: "+676", country: "Tonga", flag: "🇹🇴" },
    { code: "+1868", country: "Trinidad and Tobago", flag: "🇹🇹" },
    { code: "+216", country: "Tunisia", flag: "🇹🇳" },
    { code: "+90", country: "Turkey", flag: "🇹🇷" },
    { code: "+993", country: "Turkmenistan", flag: "🇹🇲" },
    { code: "+688", country: "Tuvalu", flag: "🇹🇻" },
    { code: "+256", country: "Uganda", flag: "🇺🇬" },
    { code: "+380", country: "Ukraine", flag: "🇺🇦" },
    { code: "+971", country: "United Arab Emirates", flag: "🇦🇪" },
    { code: "+44", country: "United Kingdom", flag: "🇬🇧" },
    { code: "+1", country: "United States", flag: "🇺🇸" },
    { code: "+598", country: "Uruguay", flag: "🇺🇾" },
    { code: "+998", country: "Uzbekistan", flag: "🇺🇿" },
    { code: "+678", country: "Vanuatu", flag: "🇻🇺" },
    { code: "+39", country: "Vatican City", flag: "🇻🇦" },
    { code: "+58", country: "Venezuela", flag: "🇻🇪" },
    { code: "+84", country: "Vietnam", flag: "🇻🇳" },
    { code: "+967", country: "Yemen", flag: "🇾🇪" },
    { code: "+260", country: "Zambia", flag: "🇿🇲" },
    { code: "+263", country: "Zimbabwe", flag: "🇿🇼" }
  ];
  
  export const usUniversities = [
    "Arizona State University, Tempe, Arizona (All UG programs), (PG -Thunderbird School of Global Management)",
    "University of Arizona, Tucson, Arizona",
    "Virginia Commonwealth University, Richmond, Virginia (Only UG)",
    "Colorado State University, Fort Collins, Colorado",
    "George Mason University, Fairfax County, Virginia",
    "West Virginia University, Morgantown, West Virginia",
    "Oregon State University, Corvallis, Oregon",
    "University of South Florida, Tampa, Florida",
    "Saint Louis University, St. Louis, Missouri",
    "Washington State University, Pullman, Washington",
    "University of Alabama at Birmingham",
    "Suffolk University, Boston, Massachusetts",
    "Marshall University Huntington, West Virginia",
    "Illinois State University, Normal, Illinois",
    "Drew University, Madison, New Jersey",
    "University of Vermont, Burlington, Vermont (UG & Only PG Pathway)",
    "University of Tulsa, Tulsa, Oklahoma (Only UG)",
    "Baylor University, Waco, Texas (Only UG)",
    "Auburn University, Alabama",
    "University of Utah, Salt Lake City, Utah (Only UG)",
    "University of Illinois at Chicago, Illinois (Only UG)",
    "University of Cincinnati, Ohio",
    "Ohio University, Athens, Ohio (Only UG)",
    "Northeastern University, Boston, Massachusetts -D`Amore-McKim School of Business, The College of Professional Studies (CPS)",
    "Brandeis International Business School (IBS), Waltham, Massachusetts",
    "University of Dayton, Dayton, Ohio",
    "University of Colorado Denver, Colorado",
    "Graduate School at UMBC, University of Maryland, Baltimore County",
    "The City College of New York, New York",
    "University of Albany, The State University of New York, Albany (SUNY Albany)",
    "SUNY Polytechnic Institute, Utica, New York",
    "The State University of New York at New Paltz (SUNY New Paltz)",
    "State University of New York at Fredonia (UG and PG Programs)",
    "State University of New York at Brockport (SUNY Brockport)",
    "State University of New York at Plattsburgh (SUNY Plattsburgh)",
    "State University of New York College at Old Westbury, New York",
    "American University Washington D.C.",
    "University of South Carolina, Columbia, South Carolina",
    "University of the Pacific, Stockton, California (Only UG)",
    "University of Kansas, Lawrence, Kansas (Only UG)",
    "Louisiana State University, Baton Rouge, Louisiana (Only UG)",
    "The University of Nebraska-Lincoln (Only UG)",
    "Missouri University of Science & Technology, Public land grant university in Rolla, Missouri",
    "University of Massachusetts, Lowell, Massachusetts",
    "University of Massachusetts, Dartmouth, Massachusetts (UG/PG Pathway)",
    "University of Massachusetts, Boston, Massachusetts",
    "Massachusetts College of Pharmacy and Health Sciences, Boston, Massachusetts (MCPHS University)",
    "University of New Hampshire, Durham, New Hampshire",
    "Adelphi University, Garden City, New York",
    "University of Central Florida, Orlando, Florida (Only UG)",
    "University of Idaho, Moscow, Idaho",
    "San Jose State University, San Jose, California",
    "San Francisco State University, San Francisco, California",
    "California State University, Northridge",
    "California State University, Fresno",
    "California State University, East Bay",
    "California State University, Channel Islands",
    "California State University, Sacramento",
    "California State University, Bakersfield",
    "California State University, Dominguez Hills",
    "California State University, Stanislaus",
    "California State University, San Bernardino",
    "California State University, Monterey Bay",
    "California Baptist University, Riverside",
    "Sonoma State University, Rohnert Park",
    "New Jersey Institute of Technology, Newark, New Jersey",
    "Florida Institute of Technology, Melbourne, Florida",
    "Pace University, New York",
    "University of Hartford (International Pathway and UG, PG Direct entry)",
    "Florida International University, Miami, Florida",
    "University of St. Thomas, Saint Paul, Minnesota",
    "Kent State University, Kent, Ohio",
    "Loyola University, New Orleans, Louisiana",
    "Nebraska Wesleyan University Lincoln (Only UG)",
    "Mississippi State University, Mississippi",
    "University of New Mexico, Albuquerque",
    "University of Nevada, Reno",
    "Wright State University, Dayton, Ohio",
    "Wichita State University, Wichita, Kansas",
    "Northern Arizona University, Flagstaff, Arizona",
    "University of North Texas, Denton, Texas",
    "University of Missouri–St. Louis (UMSL), Missouri",
    "The University of Memphis, Memphis, Tennessee",
    "Tennessee Tech University, Cookeville, Tennessee",
    "Texas State University, San Marcos, Texas",
    "Florida Atlantic University, Boca Raton, Florida (UG /PG Pathway)",
    "National Louis University, Chicago, Illinois",
    "Montana State University, Bozeman, Montana",
    "Gannon University, Erie, Pennsylvania",
    "Milwaukee School of Engineering, Milwaukee, Wisconsin",
    "Auburn University at Montgomery, Alabama",
    "Long Island University, Post, New York",
    "Long Island University, Brooklyn, New York",
    "Midwestern State University, Wichita Falls, Texas",
    "Texas A & M University, Corpus Christi, Texas",
    "Western Kentucky University, Bowling Green, Kentucky",
    "Southeast Missouri State University, Cape Girardeau, Missouri",
    "Youngstown State University, Youngstown, Ohio",
    "Purdue University Northwest, Hammond and Westville, Indiana, United States",
    "Arkansas State University, Jonesboro, Arkansas",
    "Roosevelt University, Chicago, Illinois",
    "DePaul University (Global Pathway and UG, PG Direct entry)",
    "University of New Haven, West Haven, Connecticut",
    "Humboldt State University, Arcata, California",
    "Widener University, Chester, Pennsylvania",
    "Dakota State University, Madison, South Dakota",
    "Pittsburg State University, Pittsburg, Kansas",
    "University of Bridgeport, Bridgeport, Connecticut",
    "New York Institute of Technology, New York",
    "Murray State University, Murray, Kentucky",
    "Duquesne University, Pittsburgh, Pennsylvania",
    "Quinnipiac University, Hamden, Connecticut",
    "University of Central Oklahoma, Edmond, Oklahoma",
    "Lawrence Technological University, Southfield, Michigan",
    "Saint Leo University, St. Leo, Florida",
    "Johnson & Wales University, Providence, Rhode Island",
    "Northwest Missouri State University, Maryville, Missouri",
    "California Lutheran University, Thousand Oaks, California ( School of Management)",
    "Pacific Lutheran University, Tacoma, Washington (International Pathway and UG, PG programs)",
    "Ashland University, Ashland, Ohio",
    "Indiana State University, Terre Haute, Indiana",
    "University of Tampa, Florida, USA",
    "University of Nebraska, Kearney, Nebraska (only UG)",
    "Mercer University, Macon, Georgia",
    "Southern New Hampshire University, Manchester, New Hampshire",
    "National University, San Diego, California",
    "Troy University, Troy, Alabama",
    "Texas Wesleyan University, Fort Worth, Texas",
    "Dallas Baptist University, Dallas, Texas",
    "Thomas Jefferson University, Philadelphia, Pennsylvania",
    "Western New England University, Springfield, Massachusetts",
    "Rivier University, Nashua, New Hampshire",
    "Missouri Western State University, Missouri",
    "Northwood University, Midland, Michigan (Only UG)",
    "St. Thomas University, Miami Gardens, Florida",
    "Rider University, Lawrenceville, New Jersey",
    "Atlantis University, Miami, Florida",
    "Valparaiso University, Valparaiso, Indiana",
    "Oglethorpe University, Atlanta, Georgia (Only UG)",
    "Saginaw Valley State University, University Center, Michigan",
    "Slippery Rock University, Slippery Rock, Pennsylvania",
    "Trine University, Angola, Indiana",
    "Golden Gate University, San Francisco, California (Only PG)",
    "Marymount California University, Rancho Palos Verdes, California",
    "University of Wisconsin-Eau Claire, Wisconsin",
    "University of Wisconsin–La Crosse, Wisconsin",
    "Charleston Southern University, Charleston, South Carolina",
    "DeVry University, Downers Grove, Illinois",
    "James Madison University, Harrisonburg, Virginia (Only UG)",
    "Tiffin University, Ohio",
    "Academy of Art University, San Francisco, California",
    "Full Sail University, Winter Park, Florida",
    "Kendall College Chicago, Illinois",
    "Cleary University, Howell, Michigan",
    "New York Film Academy, New York City",
    "Upper Iowa University, Fayette, Iowa",
    "Briar Cliff University, Sioux city, Iowa",
    "Oklahoma City University, Oklahoma City, Oklahoma",
    "Webster University, Missouri",
    "The University of Findlay, Findlay, Ohio",
    "Hult International Business School Boston, San Francisco campus",
    "Schiller International University, Largo, Florida",
    "Concordia University Chicago, River Forest, Illinois",
    "University of Mary Hardin-Baylor, Belton, Texas",
    "Lipscomb University, Nashville, Tennessee (Only UG)",
    "Western Washington University, Bellingham, Washington",
    "New England Institute of Technology, East Greenwich, Rhode Island",
    "Marist College, Poughkeepsie, New York",
    "Mississippi College, Clinton, Mississippi",
    "Manhattan College, Riverdale, New York",
    "Monroe College, Bronx, New York",
    "New England College, Henniker, New Hampshire",
    "Stevens Henager College, Salt Lake, Utah (Work- Study Option)",
    "Berkeley College, New York",
    "Rocky Mountain College of Art & Design, Lakewood, Colorado",
    "Canisius College, Buffalo, New York",
    "Bellevue College, Bellevue, Washington",
    "St. Thomas Aquinas College, Sparkill, New York",
    "Richard Bland College of William & Mary, Petersburg, Virginia",
    "Agnes Scott University, Decatur, Georgia",
    "Fisher College, Boston, Massachusetts",
    "Merrimack College, North Andover, Massachusetts (PG Pathway)",
    "Metropolitan College of New York, New York City, New York",
    "Green River Community College, Auburn, Washington",
    "Seattle Central Community College, Seattle, Washington",
    "Shoreline Community College, Washington",
    "Hillsborough Community College, Tampa, Florida",
    "San Mateo College of Silicon Valley, San Mateo, California",
    "Santa Ana College, California",
    "American Honors, Washington, D.C (National Transfer Network)",
    "Colorado Mesa University, Colorado",
    "Husson University, Bangor, Maine",
    "Capital University, Ohio",
    "Metropolitan State University of Denver, Colorado",
    "Manhattanville College, New York",
    "On Campus University of Rochester (UG University Transfer Program)",
    "On Campus University of Rhode Island, Kingston (UG University Transfer Program)",
    "On Campus Boston Wheelock College (UG University Transfer Program)",
    "On Campus California State Monterey Bay (UG University Transfer Program)",
    "On Campus SUNY Morrisville State College (UG University Transfer Program)",
    "On Campus Texas at University of North Texas (UG University Transfer Program)",
    "University of California, Berkeley Extension, California",
    "UCSC Silicon Valley Extension (For Certificate Programs and Pre Sessional English)",
    "University of California, Riverside Extension",
    "Aviation Institute of Maintenance",
    "Drexel University, English Language Center, Philadelphia, Pennsylvania (For ELC Programs)",
    "California State University, Los Angeles (ELP Programs at UG/PG Level)",
    "Kaplan Test Prep, a division of Kaplan",
    "Summer Discovery. Discovery Internship and Jr. Internship."
  ];
  
  export const uKUniversities = [
    "University of Bristol, Bristol, England",
    "University of Glasgow, Glasgow, Scotland",
    "University of Southampton, Southampton, England",
    "Durham University, Durham, England",
    "University of Birmingham, Birmingham, England",
    "University of Leeds, Leeds, England",
    "University of Sheffield, Sheffield, England",
    "University of Nottingham, Nottingham, England",
    "Cranfield University, Cranfield, England",
    "Queen Mary University of London, London, England",
    "Lancaster University, Lancaster, England",
    "Newcastle University, Newcastle upon Tyne, England",
    "The University of Exeter, Exeter, England",
    "University of York, York, England",
    "University of Bath, Bath, England",
    "University of Liverpool, Liverpool, England",
    "University of Aberdeen, Aberdeen, Scotland",
    "Loughborough University, Loughborough & London, England",
    "Queen`s University Belfast, Belfast, Northern Ireland",
    "University of Leicester, Leicester, England",
    "University of Surrey, Guildford, England",
    "University of Strathclyde, Glasgow, Scotland",
    "Heriot Watt University, Edinburgh, Scotland",
    "Royal Holloway, University of London, Egham, England",
    "University of Dundee, Dundee, Scotland",
    "University of East of Anglia, Norwich, England",
    "City University London, London, England",
    "Brunel University London, London, England",
    "Oxford Brookes University, Oxford, England",
    "University of Essex, Colchester, England",
    "Swansea University, Swansea, Wales",
    "Aberystwyth University, Aberystwyth, Wales",
    "University of Stirling, Stirling, Scotland",
    "Aston University, Birmingham, England",
    "University of Chichester, Chichester, England",
    "Coventry University, Coventry & London, England",
    "Kingston University, Kingston, England",
    "Bangor University, Bangor, Wales",
    "University of Portsmouth, Portsmouth, England",
    "University of Bradford, Bradford, England",
    "St George's University of London, London, England",
    "Northumbria University, Newcastle upon Tyne & London, England",
    "University of Plymouth, Plymouth, England",
    "University of Westminster, London, England",
    "Middlesex University, London, England",
    "University of Greenwich, London, England",
    "The University of Huddersfield, Huddersfield, England",
    "Bournemouth University, Poole, England",
    "Keele University, Keele, England",
    "London South Bank University, London, England",
    "Nottingham Trent University, Nottingham, England",
    "Birmingham City University, Birmingham, England",
    "De Montfort University, Leicester, England",
    "Edinburgh Napier University, Edinburgh, Scotland",
    "Glasgow Caledonian University, Glasgow & London, Scotland & England",
    "Manchester Metropolitan University, Manchester, England",
    "Sheffield Hallam University, Sheffield",
    "University of Brighton, Brighton, England",
    "University of Central Lancashire, Preston, England",
    "University of Hertfordshire, Hatfield, England",
    "University of East London, London, England",
    "University of Salford, Manchester, England",
    "University of West of England, Bristol, England",
    "University for the Creative Arts, Farnham, England",
    "Staffordshire University, Stoke-on-Trent, England",
    "Ulster University, Birmingham & London, England",
    "University of West London, London, England",
    "University of South Wales, Cardiff, Wales",
    "Teesside University, Middlesbrough, England",
    "Cardiff Metropolitan University, Cardiff, Wales",
    "Solent University, Southampton, England",
    "Anglia Ruskin University, Cambridge & Chelmsford, England",
    "University of Chester, Chester, England",
    "Liverpool Hope University, Liverpool, England",
    "University of Worcester, Worcester, England",
    "University of Gloucestershire, Gloucester, England",
    "The University of Northampton, Northampton, England",
    "The University of Buckingham, Buckingham, England",
    "University of Suffolk, Suffolk, England",
    "University of Sunderland, Sunderland & London, England",
    "Leeds Beckett University, Leeds, England",
    "Canterbury Christ Church University, Canterbury, England",
    "University of Winchester, Winchester, England",
    "Abertay University, Dundee, Scotland",
    "University of Wolverhampton, Wolverhampton, England",
    "York St John University, York, England",
    "University of Roehampton, London, England",
    "University of the West of Scotland, Paisley, Scotland",
    "University of Bedfordshire, Luton, England",
    "Ravensbourne University London, England",
    "University College Birmingham, Birmingham, England",
    "Regent’s University London, London, England",
    "Hult International Business School, London, England",
    "University of Law, Guildford, England",
    "Norwich University of Arts, Norwich, England",
    "Cambridge School of Visual & Performing Arts, Cambridge, England",
    "University Academy 92, Manchester, England",
    "Robert Gordon University, Aberdeen, Scotland",
    "BPP University, London, England",
    "Le - Cordon Bleu, London, England",
    "Istituto Marangoni, London, England",
    "Regent’s College London, Middlesex, England",
    "Liverpool John Moores University, Liverpool, England",
    "University of Sussex, Falmer, England",
    "Bellerbys College, Brighton, England",
    "Birkbeck, University of London, London, England",
    "The Courtauld University of Art, London, England",
    "Royal Veterinary College, University of London, London, England",
    "Goldsmiths, University of London, London, England",
    "University of Hull, Hull, England",
    "University of Reading, Reading, England",
    "St Mary’s University London International College, England",
    "Indian School of Business & Finance, India",
    "The Engineering & Design Institute of London, England",
    "University of Bolton, Bolton, England"
  ];
  
  export const canadianUniversities = [
    "McGill University’s School of Continuing Studies, Montreal, Quebec",
    "University of Waterloo, Waterloo, Ontario (Only UG)",
    "Queen's University, Kingston, Ontario (Only UG)",
    "University of Victoria, Victoria, British Columbia (Only UG)",
    "Toronto Metropolitan University, Toronto, Ontario (Only UG)",
    "York University, School of Continuing Education, Toronto, Ontario",
    "University of Guelph, Guelph, Ontario (Only UG)",
    "Dalhousie University, Halifax, Nova Scotia (M. Engg in Internetworking and all UG courses)",
    "University of Manitoba, Winnipeg, Manitoba",
    "Memorial University of Newfoundland, St. John's, Newfoundland and Labrador (Only PG)",
    "Memorial University of Newfoundland, Grenfell Campus, Newfoundland and Labrador",
    "University of Windsor, Windsor, Ontario (Only UG)",
    "University of New Brunswick, Fredericton, New Brunswick",
    "University of Regina, Regina, Saskatchewan",
    "Brock University, St. Catharine’s, Ontario",
    "Wilfrid Laurier University, Waterloo, Ontario (Only UG and Pre MBA)",
    "University of Lethbridge, Lethbridge, Alberta (Only UG)",
    "Lakehead University, Thunder Bay, Ontario",
    "Lakehead University through Georgian College, Barrie, Ontario",
    "University of Winnipeg, Winnipeg, Manitoba",
    "University of Prince Edward Island, Charlottetown, Prince Edward Island",
    "Acadia University, Wolfville, Nova Scotia (Only UG)",
    "University of Northern British Columbia, Prince George, British Columbia",
    "Thompson Rivers University, Kamloops, British Columbia",
    "Ontario Tech University, Oshawa, Ontario",
    "Mount Saint Vincent University, Halifax, Nova Scotia",
    "Trent University, Peterborough, Ontario",
    "Trinity Western University, Langley, British Columbia",
    "Royal Roads University, Victoria, British Columbia",
    "Fairleigh Dickinson University, Vancouver, British Columbia",
    "Simon Fraser University through Fraser International College, Burnaby, British Columbia (Only UG)",
    "Wilfred Laurier University through Wilfrid Laurier International College, Waterloo, Ontario (Only UG)",
    "University of Manitoba through International College of Manitoba, Winnipeg, Manitoba (Only UG)",
    "Toronto Metropolitan University through Toronto Metropolitan International College, Toronto, Ontario (Only UG)",
    "Vancouver Island University, Nanaimo, British Columbia",
    "St. Thomas University, Fredericton, New Brunswick",
    "University Canada West, Vancouver, British Columbia",
    "New York Institute of Technology, Vancouver, British Columbia",
    "Nipissing University, North Bay, Ontario",
    "Adler University, Vancouver, British Columbia",
    "King’s University College (University of Western Ontario), London, Ontario",
    "Cape Breton University, Sydney, Nova Scotia",
    "Capilano University, North Vancouver, British Columbia",
    "Kwantlen Polytechnic University, Surrey, British Columbia",
    "University of the Fraser Valley, Abbotsford, British Columbia",
    "Mount Allison University, Sackville, New Brunswick",
    "MacEwan University, Edmonton, Alberta",
    "Seneca College, Toronto, Ontario",
    "George Brown College, Toronto, Ontario",
    "Sheridan College, Oakville, Ontario",
    "Bow Valley College, Calgary, Alberta",
    "Douglas College, New Westminster, British Columbia (Except students from Punjab, Haryana and Chandigarh territory)",
    "Southern Alberta Institute of Technology (SAIT), Calgary, Alberta",
    "Niagara College, Welland, Ontario",
    "Niagara College, Toronto, Ontario",
    "Fanshawe College, London, Ontario",
    "Fanshawe College @ ILAC Toronto, Ontario",
    "Durham College, Oshawa, Ontario",
    "Confederation College, Thunder Bay, Ontario",
    "Fleming College, Peterborough, Ontario",
    "Fleming College, Toronto, Ontario",
    "North Island College, Vancouver Island, British Columbia",
    "Georgian College, Barrie, Ontario",
    "Georgian @ ILAC, Toronto, Ontario",
    "Loyalist College, Toronto, Ontario",
    "Sault College of Applied Arts and Technology, Sault Ste. Marie, Ontario (Except students from North & West India)",
    "Lakeland College, Vermilion, Alberta",
    "Cambrian College, Sudbury and Hanson Campus, Ontario",
    "Manitoba Institute of Trades and Technology, Winnipeg, Manitoba",
    "Centennial College, Toronto, Ontario (For students of Bangladesh, Malaysia, Nepal, Vietnam & Sri Lanka only)",
    "Conestoga College, Kitchener, Ontario",
    "College of New Caledonia, Prince George, British Columbia",
    "Saskatchewan Polytechnic, Saskatoon, Saskatchewan",
    "Yorkville University, Toronto and Vancouver (Except students from India, Bangladesh, and Pakistan)",
    "Toronto Film School, Toronto, Ontario (Except students from India, Bangladesh, and Pakistan)",
    "LaSalle College, Montreal and Vancouver",
    "College of the Rockies, Cranbrook, British Columbia",
    "Lethbridge College, Lethbridge, Alberta",
    "Northern Lights College, Dawson Creek, British Columbia",
    "Northern College, Timmins, Ontario",
    "St. Lawrence College, Kingston, Ontario",
    "Lambton College, Sarnia, Toronto and Mississauga Campus, Ontario",
    "Selkirk College, Castlegar, British Columbia",
    "Assiniboine Community College, Brandon, Manitoba",
    "Keyano College, Fort McMurray, Alberta (Except students of India)",
    "Canadore College, North Bay, Ontario (Except students from Punjab and Haryana)",
    "Acsenda School of Management, Vancouver, British Columbia",
    "Le Cordon Bleu, Ottawa, Ontario",
    "Alexander College, Vancouver, British Columbia",
    "Vancouver Film School, Vancouver, British Columbia",
    "Northern College at Pures-Toronto, Toronto, Ontario",
    "Vancouver Community College, Vancouver, British Columbia",
    "British Columbia Institute of Technology, Burnaby, British Columbia",
    "Medicine Hat College, Alberta, Canada",
    "NorQuest College, Edmonton, Alberta",
    "Coquitlam College, Coquitlam, British Columbia",
    "Coast Mountain College, Terrace, British Columbia",
    "Justice Institute of British Columbia, New Westminster, British Columbia",
    "Vancouver Premier College, Vancouver, British Columbia"
  ];
  
  export const irishUniversities = [
    "Trinity College Dublin, Dublin",
    "University College Dublin, Dublin",
    "Dublin City University, Dublin (Pathway as well as UG & PG Direct Entry)",
    "Technological University Dublin, Dublin (Pathway as well as UG & PG Direct Entry)",
    "National College of Ireland, Dublin",
    "Dublin Business School, Dublin",
    "Griffith College, Dublin, Cork and Limerick (Campus in 3 cities)",
    "CCT College Dublin, Dublin"
  ];
  
  export const australianUniversities = [
    "The University of New South Wales, Sydney (CRICOS Code 00098G)",
    "The University of Queensland, Brisbane (CRICOS Code 00025B)",
    "Monash University, Melbourne (CRICOS Code 00008C)",
    "University of Western Australia, Perth (INTO) (CRICOS Code: 00126G)",
    "The University of Adelaide, Adelaide (CRICOS Code 00123M)",
    "University of Technology Sydney, Sydney (CRICOS Provider No. 00099F)",
    "University of Wollongong, Wollongong (CRICOS Code 00102E)",
    "RMIT University, Melbourne (CRICOS Code 00122A)",
    "The University of Newcastle, Newcastle (CRICOS Code 00109J)",
    "Curtin University, Perth (CRICOS Code 00301J)",
    "Macquarie University, Sydney (CRICOS Code 00002J)",
    "Queensland University of Technology, Brisbane (CRICOS Code 00213J)",
    "Deakin University, Melbourne & Geelong (CRICOS Code 00113B)",
    "University of Tasmania, Hobart, Launceston & Sydney (CRICOS Code 00586B)",
    "Swinburne University of Technology, Melbourne (CRICOS Code 00111D)",
    "Griffith University, Gold Coast & Brisbane (CRICOS Code 00233E)",
    "La Trobe University, Melbourne & Sydney (CRICOS Codes: Mel-03312D & Syd-00115M)",
    "University of South Australia, Adelaide (CRICOS Code 00121B)",
    "Flinders University, Adelaide (CRICOS Code 00114A)",
    "James Cook University, Townsville, Cairns, & Brisbane (CRICOS Code 00117J)",
    "Western Sydney University, Sydney (Paramatta & City campuses) (CRICOS Code 00917K)",
    "CQUniversity Australia, Sydney, Melbourne, Brisbane & Perth (CRICOS Code 00219C)",
    "University of Southern Queensland, Toowoomba (CRICOS Code: 02225M)",
    "Southern Cross University, Gold Coast, Lismore and Coffs Harbour (CRICOS Code 01241G)",
    "Australian Catholic University, North Sydney, Melbourne, Brisbane, Canberra, Adelaide (CRICOS Code 00004G)",
    "Charles Sturt University, Wagga Wagga (CRICOS Code 00005F)",
    "Torrens University, Adelaide, Melbourne & Sydney (CRICOS Provider Code: 03389E)",
    "Education Centre Australia (CRICOS Code 02644C)",
    "Kent Institute Australia, Sydney (CRICOS Code - 00161E)",
    "Le Cordon Bleu, Adelaide, Sydney, Melbourne & Perth (CRICOS Code 02380M)",
    "Blue Mountains International Hotel Management School, Adelaide (CRICOS Provider Code: 03389E)",
    "International College of Management Sydney (CRICOS Code 01484M)",
    "Engineering Institute of Technology, Perth (CRICOS No: 03567C)",
    "Academy of Information Technology, Sydney (CRICOS Code: 02155J)",
    "Excelsia College, Sydney (CRICOS Code 02664K)",
    "Ironwood Institute Adelaide, Adelaide (CRICOS Code: 03039E)",
    "International College of Hotel Management, Adelaide (CRICOS Code 02914G)",
    "Airways Aviation, Gold Coast and Sunshine Coast (CRICOS Code: 00296A)",
    "Australian College of Applied Psychology, Sydney (CRICOS Code 01328A)",
    "UNSW Global, Sydney (CRICOS Code 00098G)",
    "The University of Adelaide College (CRICOS Code 00123M)",
    "UTS College, Sydney (CRICOS Provider Codes: UTS College 00859D, UTS 00099F)",
    "The University of Newcastle College of International Education, Newcastle (CRICOS 00109J)",
    "Curtin College, Perth (CRICOS Code 02042G)",
    "Deakin College, Melbourne (CRICOS Code 01590J)",
    "South Australia Institute of Business & Technology, Adelaide (CRICOS Code 02193C)",
    "Griffith College, Gold Coast & Brisbane (CRICOS Code 01737F)",
    "La Trobe College, Melbourne (CRICOS Code 03312D)",
    "Sydney Institute of Business & Technology, Sydney (CRICOS code 01576G)",
    "Edith Cowan College (CRICOS Code 01312J)",
    "Eynesbury College, Adelaide (CRICOS Code 00561M)",
    "University of Canberra College, Canberra (CRICOS Code 00212K)",
    "TAFE Queensland, Brisbane (CRICOS Code 03020E)",
    "Russo Business School, Brisbane (CRICOS Code – 03441F)",
    "Charles Darwin University International College (CRICOS Codes: 0100739; 0100740)",
    "Dolph Business School, Reservoir (CRICOS Code: 03642G)",
    "Sarina Russo Institute, Brisbane (CRICOS Code 00607B)",
    "Australia Institute of Business and Technology, Upper Mount Gravatt (CRICOS Code: 03430J & 03610E)",
    "Australian Health and Management Institute, Parramatta (CRICOS Code: 03595K)",
    "Intensive English Language Institute, Perth (CRICOS Code: 062875B)",
    "Reach Community College, Hobart (CRICOS Code: 03904B)",
    "LaSalle College, Melbourne (CRICOS Code 02201G)"
  ];
  
  
  export const newZealandUniversities = [
    "University of Auckland, Auckland",
    "Victoria University of Wellington, Wellington",
    "University of Canterbury, Christchurch",
    "Massey University, Palmerston North",
    "University of Waikato, Hamilton, North Island",
    "Lincoln University, Lincoln",
    "Auckland University of Technology, Auckland",
    "Unitec Institute of Technology- Te Pūkenga, Auckland",
    "Otago Polytechnic- Te Pūkenga, Dunedin & Auckland",
    "Manukau Institute of Technology- Te Pūkenga, Auckland",
    "Ara Institute of Canterbury- Te Pūkenga, Christchurch",
    "Eastern Institute of Technology- Te Pūkenga, Napier",
    "Nelson Marlborough Institute of Technology (NMIT)- Te Pūkenga, Nelson & Blenheim",
    "Whitireia New Zealand- Te Pūkenga, Porirua",
    "Southern Institute of Technology- Te Pūkenga, Invercargill",
    "Wellington Institute of Technology (WelTec)- Te Pūkenga, Wellington",
    "Western Institute of Technology at Taranaki (WITT)- Te Pūkenga, New Plymouth",
    "North Tec- Te Pūkenga, Whangarei",
    "Toi Ohomai Institute of Technology- Te Pūkenga, Rotorua & Tauranga",
    "Pacific International Hotel Management School, New Plymouth",
    "UC International College, Christchurch",
    "Taylors College, Auckland",
    "University of Waikato College, Hamilton",
    "Whitecliffe College of Arts and Design, Auckland & Christchurch",
    "Whitecliffe College of Fashion and Sustainability, Auckland & Wellington",
    "Whitecliffe College of Technology & Innovation, Auckland, Wellington & Christchurch",
    "Aspire2International Group, Auckland, Wellington, Tauranga & Christchurch",
    "Le Cordon Bleu, Wellington",
    "New Zealand Airline Academy, Oamaru"
  ];
  
  export const singaporeUniversities = [
    "National University of Singapore (Only SCALE courses)",
    "Technical University of Munich Asia (Only PG)",
    "S P Jain School of Global Management",
    "SIM Global Education",
    "Curtin Singapore",
    "James Cook University (JCU)",
    "Management Development Institute of Singapore (MDIS)",
    "PSB Academy",
    "Kaplan Higher Education Academy (KHEA)",
    "Raffles College of Higher Education",
    "William Angliss Institute",
    "EAIM- East Asia Institute of Management",
    "Nanyang Institute of Management",
    "Educare Global Academy (EGA)"
  ];
  
  export const switzerlandUniversities = [
    "GLION Institute of Higher Education, Montreux",
    "EU Business School, Montreux and Geneva",
    "Business & Hotel Management School (BHMS), Lucerne",
    "Swiss Hotel Management School (SHMS), Montreux and Leysin",
    "Geneva Business School, Geneva",
    "International Management Institute (IMI), Luzern",
    "Cesar Ritz, Montreux",
    "International Hotel & Tourism Training Institute (IHTTI), Montreux",
    "International University in Geneva, Geneva",
    "Hotel & Tourism Management Institute Switzerland (HTMi), Lucerne",
    "Les Roches, Montana",
    "Culinary Arts Academy (CAA), Le Bouveret and Lucerne",
    "Hotel Institute Montreux (HIM), Montreux",
    "American University in Switzerland"
  ];
  